export const GET_ALLUSERS = 'GET_ALLUSERS';
export const GET_ALLPOSTS = 'GET_ALLPOSTS';
export const GET_ALLEVENTS = 'GET_ALLEVENTS';
export const GET_ALLPRODUCTS = 'GET_ALLPRODUCTS';
export const GET_ALLTHREADS = 'GET_ALLTHREADS';
export const GET_ONETHREAD = 'GET_ONETHREAD';
export const SEARCH_THREAD = 'SEARCH_THREAD';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL  = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT' ;
export const CLEAR_PROFILE = 'CLEAR_PROFILE';
export const AUTH_ERROR = 'AUTH_ERROR';
export const  USER_LOADED = 'USER_LOADED';
export const ERROR__THREAD = 'ERROR__THREAD';
export const SEARCH_THREAD_ERROR = 'SEARCH_THREAD_ERROR';
export const ERROR_EVENT = 'ERROR_EVENT';
export const GET_ONEPRODUCT = 'GET_ONEPRODUCT';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const GET_ONEEVENT = 'GET_ONEEVENT'; 


